name: Release

on:
  push:
    tags:
      - 'v*' # 当推送 v 开头的 tag 时触发

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04 
    strategy:
      matrix:
        go-version: [ '1.24.5' ] 
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
        exclude:
          # 排除 darwin/arm64 组合
          - os: darwin
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download dependencies
        run: |
          go mod download
          go mod tidy

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          PROJECT_NAME: ${{ github.event.repository.name }}
          CGO_ENABLED: 0
        run: |
          mkdir -p bin
          OUTPUT="bin/${PROJECT_NAME}-${GOOS}-${GOARCH}"
          if [ "${GOOS}" = "windows" ]; then
            OUTPUT="$OUTPUT.exe"
          fi
          go build -ldflags="-s -w" -o $OUTPUT .

      - name: Compress binaries
        run: |
          cd bin
          for file in *; do
            if [[ "$file" == *.exe ]]; then
              zip "${file%.exe}.zip" "$file" "../config-template.yaml"
            else
              tar -czvf "$file.tar.gz" "$file" "../config-template.yaml"
            fi
            rm "$file"
          done

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4 # 更新到 v4 版本
      #   with:
      #     name: binaries
      #     path: bin/
      #     retention-days: 1 # 可选：设置 artifacts 保留天数

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}